### PR TITLE
Fix webauthn for local deployments

### LINKED ISSUE #355: Webauthn script not loaded on localhost due to Content Security Policy violation
The passwordless login method is broken in the latest login ui version.
To reproduce:
1. Run the docker compose with login ui image >v0.17.0, create a hydra client and run grafana.
2. Go to localhost:2345, log in with the test user.
3. Go to localhost:4455/ui/setup_passkey. Insert any key name and click on Add. The console will display the following errors:
```
Refused to load the script 'http://localhost:4433/.well-known/ory/webauthn.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' 'unsafe-eval'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

framework-2c16ac744b6cdea6.js:9 Uncaught TypeError: r.__oryWebAuthnRegistration is not a function
    at onClick (127-3320e06beedeceb7.js:1:2103)
    at Object.eU (framework-2c16ac744b6cdea6.js:9:14908)
    at eH (framework-2c16ac744b6cdea6.js:9:15062)
    at framework-2c16ac744b6cdea6.js:9:33368
    at re (framework-2c16ac744b6cdea6.js:9:33467)
    at rn (framework-2c16ac744b6cdea6.js:9:33881)
    at framework-2c16ac744b6cdea6.js:9:39337
    at oN (framework-2c16ac744b6cdea6.js:9:96304)
    at eF (framework-2c16ac744b6cdea6.js:9:14046)
    at ro (framework-2c16ac744b6cdea6.js:9:35172)
```

Due to this error, the webauthn.js script is not loaded and the QR code pop-up is not shown.

This seems to be caused by https://github.com/canonical/identity-platform-login-ui/pull/299 (I tried removing the changes it introduced and the script was loaded correctly).

### PR DESCRIPTION
**Pull request by nsklikas**
IAM-1187

Closes #355 

Introduces a new flag that allows localhost:* for the script-src.

I removed `unsafe-inline` from the `script-src`, I could not remove it from the `style-src` because it is required from some library. (cc @edlerd). IMHO we should remove `unsafe-inline` and explicitly specify the hashes of the scripts that we allow to use inline, I would expect this to be handled at the proxy rather than the app itself.

### CODE REVIEW

**Comment by nsklikas** [comment]
Decided not to use a new flag and just compare the 2 URLs, this seems cleaner.

File: pkg/ui/handlers.go [hunk 1]
```diff
@@ -62,11 +68,24 @@ func (a *API) uiFiles(w http.ResponseWriter, r *http.Request) {
 	a.fileServer.ServeHTTP(w, r)
 }
 
-func NewAPI(fileSystem fs.FS, logger logging.LoggerInterface) *API {
+func (a *API) getCSP(baseURL, kratosPublicURL string) string {
+	b, _ := url.Parse(baseURL)
+	k, _ := url.Parse(kratosPublicURL)
+	if k != nil && b != nil && k.Host != b.Host {
```
Comment (nsklikas) [inline pkg/ui/handlers.go:74]: Parsing the URLs may fail, this is swallowed here because the `BaseURL` is not a required parameter. Since this happens when the application starts, we could also panic to force the user to provide valid config.

File: pkg/ui/handlers.go [hunk 2]
```diff
@@ -62,11 +68,24 @@ func (a *API) uiFiles(w http.ResponseWriter, r *http.Request) {
...
+		// We need to whitelist the kratos URL, because the browser needs to fetch the webauthn.js script from Kratos
+		return fmt.Sprintf("default-src 'self' data: https://*.ubuntu.com; script-src 'self' %v; style-src 'self' 'unsafe-inline'", kratosPublicURL)
+	}
+	return "default-src 'self' data: https://*.ubuntu.com; script-src 'self'; style-src 'self' 'unsafe-inline'"
```
Comment (BarcoMasile) [inline pkg/ui/handlers.go:78]: suggestion: feel free to disregard the code suggestion but consider the edit to the comment to comply with company guidelines

```suggestion
        additionalScriptURL := ""
	if k != nil && b != nil && k.Host != b.Host {
		// Allowlist the kratos URL to allow the browser needs to fetch the webauthn.js script
		additionalScriptURL := kratosPublicURL
	}
	return fmt.Sprintf("default-src 'self' data: https://*.ubuntu.com; script-src 'self' %v; style-src 'self' 'unsafe-inline'", additionalScriptURL)
```

Comment (nsklikas) [reply pkg/ui/handlers.go]: Oh nice, that's better. Thank you

**Review by natalian98 — APPROVED** [review]

**Review by BarcoMasile — APPROVED** [review]

**Review by edlerd — APPROVED** [review]
Good move forward to make the CSP a bit tighter.
